from typing import Optional, TypedDict


class WorkflowState(TypedDict):
    # Session identity
    session_id: str
    thread_id: str
    filename: str

    # Stage 1: raw text extracted from document
    raw_text: str

    # Stage 2: concept nodes extracted by LLM
    concept_nodes: list[dict]  # list of ConceptNode.model_dump()

    # Stage 3: clarifying questions generated by LLM
    clarifying_questions: list[dict]  # list of ClarifyingQuestion.model_dump()

    # Stage 4: human-submitted answers (injected via update_state before resume)
    clarification_answers: list[dict]  # [{concept_id, question_text, answer}]

    # Stage 5: drafted / refined user stories
    stories: list[dict]  # list of UserStory.model_dump()

    # Stage 6: human review signal
    # Empty string or None → approve and export; non-empty → refine
    refinement_feedback: Optional[str]

    # Workflow control
    status: str  # processing | awaiting_clarification | awaiting_review | complete | error
    error_message: Optional[str]

    # Export
    artifact_path: Optional[str]

    # Supporting documents (optional multi-upload)
    supporting_doc_paths: list[str]         # raw upload paths — consumed by index_supporting_docs
    supporting_filenames: list[str]         # original filenames for display
    supporting_summaries: list[str]         # LLM-generated summary per doc; set by index_supporting_docs
    supporting_context_mode: Optional[str]  # "full" | "rag" | None (None = no supporting docs)
    supporting_index_path: Optional[str]    # FAISS index dir; only set in "rag" mode
